# FUTWIZ BASE URL
FUTWIZ_BASE_URL = "https://www.futwiz.com"
FUTWIZ_PLAYERS_URL = "https://www.futwiz.com/en/fc24/players"

# DIV CLASS NAMES
DIV_PLAYER_POSITION = "card-24-position"
DIV_PLAYER_ALT_POSITION = "card-24-extra-info-txt"
DIV_PLAYER_MARKET_VALUE = "price-num"
DIV_PLAYER_OVERALL_RATING = "card-24-rating"
DIV_PLAYER_DETAILS_DATA = "player-details-inner"

# PLAYER STATS
DIV_PLAYERS_ALL_STATS_IN_GAMES = "player-stats-ingames"

# A TAG CLASS NAMES
A_PLAYERS_LIST = "latest-player-card"

# PLAYERS
NO_PLAYERS_PER_PAGE = 28

# CARD VERSION DIVS
DIV_GOLD_CARD_RARE = "card-24 card-24-gold"
DIV_GOLD_CARD_BASIC = "card-24 card-24-gold-nr"
DIV_SILVER_CARD_RARE = "card-24 card-24-silver"
DIV_SILVER_CARD_BASIC = "card-24 card-24-silver-nr"
DIV_BRONZE_CARD_RARE = "card-24 card-24-bronze-nr"
DIV_BRONZE_CARD_BASIC = "card-24 card-24-bronze"

# CARD VERSIONS LIST

CARD_VERSION_MAP = {
    DIV_GOLD_CARD_RARE: "GOLD RARE",
    DIV_GOLD_CARD_BASIC: "GOLD",
    DIV_SILVER_CARD_RARE: "SILVER RARE",
    DIV_SILVER_CARD_BASIC: "SILVER",
    DIV_BRONZE_CARD_RARE: "BRONZE RARE",
    DIV_BRONZE_CARD_BASIC: "BRONZE"
}
