# PROXY SERVERS
USE_PROXY = True
PROXY_SERVERS_FILE_PATH = r""

# THREADS
NO_WORKING_THREADS = 10
DELAY_BETWEEN_REQUESTS_S = 0

# REQUESTS
MAX_RETRIES = 30
DELAY_BETWEEN_TO_RETRY = 2

# CSV LOGGING
INCLUDE_PLAYER_STATS = True
