# PROXY SERVERS
USE_PROXY = True
PROXY_SERVERS_FILE_PATH = r"C:\Users\bniem\Downloads\proxyscrape_premium_http_proxies.txt"

# THREADS
NO_WORKING_THREADS = 5
DELAY_BETWEEN_REQUESTS_S = 0

# REQUESTS
MAX_RETRIES = 10
DELAY_BETWEEN_TO_RETRY = 2.5

# CSV LOGGING
INCLUDE_PLAYER_STATS = True
LOGGING_THREAD_DELAY = 0.07
CSV_FILE_NAME = "fut_players.csv"
