# PROXY SERVERS
USE_PROXY = True
PROXY_SERVERS_FILE_PATH = r""

# THREADS
NO_WORKING_THREADS = 10
DELAY_BETWEEN_REQUESTS_S = 0

# REQUESTS
MAX_RETRIES = 20
DELAY_BETWEEN_TO_RETRY_S = 3

# CSV LOGGING
INCLUDE_PLAYER_STATS = True
LOGGING_THREAD_DELAY_S = 0.05
CSV_FILE_NAME = "fut_players.csv"
